export const FETCH_INSTITUTIONS = 'FETCH_INSTITUTIONS';
export const CREATE_INSTITUTION = 'CREATE_INSTITUTION';
export const DELETE_INSTITUTION = 'DELETE_INSTITUTION';
export const UPDATE_INSTITUTION = 'UPDATE_INSTITUTION';