export const FETCH_CONSTRAINS = 'FETCH_CONSTRAINS';
export const CREATE_CONSTRAIN = 'CREATE_CONSTRAIN';
export const UPDATE_CONSTRAIN = 'UPDATE_CONSTRAIN';
export const REMOVE_CONSTRAIN = 'REMOVE_CONSTRAIN';