

const CODE_OK = 200;
const CODE_CREATED = 201;
const CODE_ACCEPTED = 202;
const CODE_NON_AUTH_INFO = 203;
const CODE_NO_CONTENT = 204;

const CODE_ERROR = 555;
const ERROR_FIELD_ALREAD_CREATED = 601;
const ERROR_NO_FIELD_KEY = 602;

module.exports = {
    CODE_OK,
    CODE_CREATED,
    CODE_ACCEPTED,
    CODE_NON_AUTH_INFO,
    CODE_NO_CONTENT,
    CODE_ERROR,
    ERROR_FIELD_ALREAD_CREATED,
    ERROR_NO_FIELD_KEY
};
